### ISSUE TITLE
unnecessary listener registration

### ISSUE THREAD

**Issue by finreinhard** [luxiboxDE/MountainCore#5]
https://github.com/luxiboxDE/MountainCore/blob/a414a7f4faa230531baba2cdf7aedc5c4bd2840d/src/main/java/de/luxibox/server/Core.java#L68

In this line you registrated the core class as a listener, but you there is no listener in it. Also you can remove the Listener implementation for this class. The same thing for the command executor :)

**Comment by luxiboxDE** [comment]
Thanks c:
